version: '3.1'

services:

  mongo:
    image: mongo
    restart: always

  healthcheck:
    test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
    interval: 10s
    timeout: 10s
    retries: 5
    start_period: 40s

    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

    networks:
      - network
    
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

    networks:
      - network
    volumes:
      - .:/app

networks:
    network:
        driver: bridge


    